[build]
  # The command to build your frontend site
  command = "npm run build"
  # The directory where the built files are located
  publish = "dist"
  # The base directory for the frontend project
  base = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://solar-explorer-backend.onrender.com/api/:splat"
  status = 200
